"""apply the model column comments to the database

PM-45's larger half. **Comments only — nothing else.**

## Why this is its own migration

`--autogenerate` proposed these 116 comment changes alongside eight index
renames. Bundling them would repeat the mistake `ae8cee95c547` exists to correct:
a migration should do the thing its name says, so somebody reading the history
can trust the name instead of reading the body.

## Why it is safe

Verified before it was written, not assumed: the generated output contains
**zero** `type_=`, **zero** bare `nullable=` and **zero** bare `server_default=`.
Every operation carries `comment=` plus `existing_*` descriptors, which are
Alembic telling itself what the column already is. Nothing about the data, the
types or the constraints changes — this is `COMMENT ON COLUMN`, which is
metadata.

## Why bother at all

These comments live in the models and had never reached the database, so every
future `--autogenerate` re-proposed all 116 of them. That is the noise a real
change hides in — and it is exactly how four constraint drops nearly rode into a
migration named after something else. With this applied, a generated diff is
short enough to actually read.

Revision ID: 0e6d123d0fa3
Revises: ae8cee95c547
Create Date: 2026-08-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
# ⚠️ Needed by the `existing_type=postgresql.TIMESTAMP(...)` descriptors below.
# Dropped when this file's header was hand-written, which failed at runtime with
# a NameError — and `alembic` prints "Running upgrade" BEFORE executing, so the
# output looked like a success until `alembic current` disagreed. Grepping for
# that line is not verification.
from sqlalchemy.dialects import postgresql

revision: str = "0e6d123d0fa3"
down_revision: Union[str, None] = "ae8cee95c547"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activity_log', 'description',
               existing_type=sa.TEXT(),
               comment="Human-readable summary, e.g. 'Ayush Mishra logged in'",
               existing_nullable=False)
    op.alter_column('activity_log', 'subject_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Model name: 'User' | 'Role' — not a namespace",
               existing_comment="Model name: 'User' | 'Role'. Not a PHP namespace",
               existing_nullable=True)
    op.alter_column('activity_log', 'subject_id',
               existing_type=sa.VARCHAR(length=36),
               comment='String because ours are UUIDs and role ids are ints; both fit',
               existing_comment='String: ours are UUIDs, and role ids are integers',
               existing_nullable=True)
    op.alter_column('activity_log', 'causer_id',
               existing_type=sa.VARCHAR(length=36),
               comment='NULL for an unauthenticated actor — a failed login has no causer',
               existing_comment='NULL when unauthenticated — a failed login has no causer',
               existing_nullable=True)
    op.alter_column('activity_log', 'batch_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='Groups rows written by one logical operation, e.g. a bulk update',
               existing_comment='Groups the rows written by one bulk operation',
               existing_nullable=True)
    op.alter_column('api_credential_schemas', 'is_encrypted',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Per field, not per credential — see the model',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('app_settings', 'logo_mime',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment="Detected from the file's magic bytes, never from the request",
               existing_nullable=True)
    op.alter_column('app_settings', 'logo_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Cache key for the ?v= query and the ETag',
               existing_nullable=True)
    op.alter_column('app_settings', 'favicon_mime',
               existing_type=sa.VARCHAR(length=60),
               comment=None,
               existing_comment="Detected from the file's magic bytes, never from the request",
               existing_nullable=True)
    op.alter_column('app_settings', 'favicon_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Cache key for the ?v= query and the ETag',
               existing_nullable=True)
    op.alter_column('error_groups', 'fingerprint',
               existing_type=sa.VARCHAR(length=32),
               comment='md5(exception_class|file|line|route). Excludes the message — see the service',
               existing_comment='md5(exception_class|file|line|route). Excludes the message',
               existing_nullable=False)
    op.alter_column('error_groups', 'module',
               existing_type=sa.VARCHAR(length=32),
               comment='Which part of the product raised it — filters the index',
               existing_nullable=False,
               existing_server_default=sa.text("'core'::character varying"))
    op.alter_column('error_groups', 'latest_message',
               existing_type=sa.TEXT(),
               comment='Most recent message. Not part of the fingerprint',
               existing_nullable=False)
    op.alter_column('error_groups', 'occurrence_count',
               existing_type=sa.INTEGER(),
               comment='Denormalised. Rows are pruned; this count is not',
               existing_comment='Denormalised. Occurrence rows are prunable; this count is not',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('error_occurrences', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment='Who hit it, when there was a session. SET NULL — the sighting outlives the account',
               existing_nullable=True)
    op.alter_column('error_occurrences', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='User agent and referer ONLY. Never request input — see the class docstring',
               existing_comment='User agent and referer ONLY. Never request input',
               existing_nullable=True)
    op.alter_column('partner_tiers', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Stable code name, referenced from app/domain/partners/tiers.py',
               existing_comment='Stable code name, referenced from app/core/partner_tiers.py',
               existing_nullable=False)
    op.alter_column('partner_tiers', 'max_listings',
               existing_type=sa.INTEGER(),
               comment='NULL means unlimited. Not a -1 sentinel — see domain/partners/tiers.py',
               existing_comment='NULL means unlimited. Not a -1 sentinel — see core/partner_tiers.py',
               existing_nullable=True)
    op.alter_column('permission_groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment="Slug, e.g. 'users'",
               existing_nullable=False)
    op.alter_column('permission_groups', 'display_order',
               existing_type=sa.INTEGER(),
               comment='Ascending sort order in the permissions UI',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('permission_groups', 'module',
               existing_type=sa.VARCHAR(length=100),
               comment="Owning module, e.g. 'core' or 'legacy'",
               existing_nullable=True)
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment="{resource}-{action}, resource singular, e.g. 'user-view'",
               existing_nullable=False)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment='Seeded role referenced by name in code; cannot be renamed or deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('search_logs', 'q',
               existing_type=sa.VARCHAR(length=255),
               comment='The raw query',
               existing_nullable=False)
    op.alter_column('searchable_entities', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment="Section heading in the results — 'Users'",
               existing_nullable=False)
    op.alter_column('searchable_entities', 'group',
               existing_type=sa.VARCHAR(length=64),
               comment='Orders and buckets the result sections',
               existing_nullable=False)
    op.alter_column('searchable_entities', 'icon',
               existing_type=sa.VARCHAR(length=50),
               comment='navIcons key. NULL renders no glyph',
               existing_nullable=True)
    op.alter_column('searchable_entities', 'display_template',
               existing_type=sa.VARCHAR(length=191),
               comment="Result title, e.g. '{first_name} {last_name}'",
               existing_nullable=False)
    op.alter_column('searchable_entities', 'subtitle_template',
               existing_type=sa.VARCHAR(length=191),
               comment="Second line, e.g. '{email}'",
               existing_nullable=True)
    op.alter_column('searchable_entities', 'route_param_field',
               existing_type=sa.VARCHAR(length=64),
               comment='Which column fills the placeholder',
               existing_nullable=False,
               existing_server_default=sa.text("'id'::character varying"))
    op.alter_column('user_invitations', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment="Stored lower-cased; must match the accepting account's email",
               existing_nullable=False)
    op.alter_column('user_invitations', 'token',
               existing_type=sa.VARCHAR(length=128),
               comment='URL-safe random token from security.generate_token()',
               existing_nullable=False)
    op.alter_column('user_invitations', 'role_id',
               existing_type=sa.INTEGER(),
               comment='Role applied on acceptance',
               existing_nullable=True)
    op.alter_column('user_invitations', 'note',
               existing_type=sa.TEXT(),
               comment='Optional message included in the email',
               existing_nullable=True)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment="The 'sid' claim in both the access and refresh tokens",
               existing_nullable=False)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment=None,
               existing_comment='45 chars fits an IPv4-mapped IPv6 address',
               existing_nullable=True)
    op.alter_column('user_sessions', 'user_agent',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Untrusted self-reported text. Display only; never decide on it',
               existing_nullable=True)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment="Mirrors the refresh token's expiry; past this the session is dead",
               existing_nullable=False)
    op.alter_column('user_sessions', 'revoked_reason',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='logout | password_change | password_reset | revoked_by_admin',
               existing_nullable=True)
    op.alter_column('user_sessions', 'refresh_token_jti',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='The one refresh token currently valid for this session',
               existing_nullable=True)
    op.alter_column('user_sessions', 'previous_refresh_jti',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Just-superseded token, honoured only inside the grace window',
               existing_nullable=True)
    op.alter_column('user_sessions', 'refresh_rotated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When the last rotation happened; bounds the grace window',
               existing_nullable=True)
    op.alter_column('user_sessions', 'password_confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When this session last re-proved the password. Per session, not per user',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Stored lower-cased; compare against a lower-cased input',
               existing_nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='bcrypt digest. NULL for Google-only accounts',
               existing_comment='plain text password (dev/test only)',
               existing_nullable=True)
    op.alter_column('users', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Set automatically for Google sign-ups',
               existing_nullable=True)
    op.alter_column('users', 'google_avatar',
               existing_type=sa.VARCHAR(length=500),
               comment='Remote URL from Google. See profile_photo_path for an upload',
               existing_nullable=True)
    op.alter_column('users', 'personal_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Personal address. NOT an identity — `email` is what signs in',
               existing_comment='Personal address. NOT used for sign-in — `email` is the identity',
               existing_nullable=True)
    op.alter_column('users', 'profile_photo_path',
               existing_type=sa.VARCHAR(length=2048),
               comment="Uploaded avatar path, as opposed to google_avatar's remote URL",
               existing_comment='Uploaded avatar path. `google_avatar` is the remote Google URL',
               existing_nullable=True)
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment='Free-text organisation name. Superseded by organisation_id — see below',
               existing_nullable=True)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('INACTIVE', 'ACTIVE', name='user_status'),
               comment='ACTIVE or INACTIVE only. ACTIVE may sign in; re-checked every request',
               existing_nullable=False,
               existing_server_default=sa.text("'INACTIVE'::user_status"))
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               comment='Consecutive failures; reset to 0 on success',
               existing_nullable=False)
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Login refused until this time after too many failures',
               existing_nullable=True)
    op.alter_column('users', 'two_factor_secret',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet-encrypted TOTP secret. NEVER stored in the clear',
               existing_nullable=True)
    op.alter_column('users', 'two_factor_recovery_codes',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Fernet-encrypted JSON array. Codes are removed as they are used',
               existing_nullable=True)
    op.alter_column('users', 'password_otp',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='bcrypt hash of the pending 6-digit password-recovery code',
               existing_nullable=True)
    op.alter_column('users', 'password_otp_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Send cooldown derives from this — sent_at is expires_at minus the TTL',
               existing_comment='When the pending code expires; send cooldown derives from this',
               existing_nullable=True)
    op.alter_column('users', 'password_otp_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Email ownership proved; lets change-password skip the current password',
               existing_nullable=True)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_otp_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Email ownership proved; lets change-password skip the current password',
               existing_nullable=True)
    op.alter_column('users', 'password_otp_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the pending code expires; send cooldown derives from this',
               existing_comment='Send cooldown derives from this — sent_at is expires_at minus the TTL',
               existing_nullable=True)
    op.alter_column('users', 'password_otp',
               existing_type=sa.TEXT(),
               comment='bcrypt hash of the pending 6-digit password-recovery code',
               existing_nullable=True)
    op.alter_column('users', 'two_factor_recovery_codes',
               existing_type=sa.TEXT(),
               comment='Fernet-encrypted JSON array. Codes are removed as they are used',
               existing_nullable=True)
    op.alter_column('users', 'two_factor_secret',
               existing_type=sa.TEXT(),
               comment='Fernet-encrypted TOTP secret. NEVER stored in the clear',
               existing_nullable=True)
    op.alter_column('users', 'locked_until',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Login refused until this time after too many failures',
               existing_nullable=True)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Consecutive failures; reset to 0 on success',
               existing_nullable=False)
    op.alter_column('users', 'status',
               existing_type=postgresql.ENUM('INACTIVE', 'ACTIVE', name='user_status'),
               comment=None,
               existing_comment='ACTIVE or INACTIVE only. ACTIVE may sign in; re-checked every request',
               existing_nullable=False,
               existing_server_default=sa.text("'INACTIVE'::user_status"))
    op.alter_column('users', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Free-text organisation name. Superseded by organisation_id — see below',
               existing_nullable=True)
    op.alter_column('users', 'profile_photo_path',
               existing_type=sa.VARCHAR(length=2048),
               comment='Uploaded avatar path. `google_avatar` is the remote Google URL',
               existing_comment="Uploaded avatar path, as opposed to google_avatar's remote URL",
               existing_nullable=True)
    op.alter_column('users', 'personal_email',
               existing_type=sa.VARCHAR(length=255),
               comment='Personal address. NOT used for sign-in — `email` is the identity',
               existing_comment='Personal address. NOT an identity — `email` is what signs in',
               existing_nullable=True)
    op.alter_column('users', 'google_avatar',
               existing_type=sa.VARCHAR(length=500),
               comment=None,
               existing_comment='Remote URL from Google. See profile_photo_path for an upload',
               existing_nullable=True)
    op.alter_column('users', 'email_verified_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='Set automatically for Google sign-ups',
               existing_nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               comment='plain text password (dev/test only)',
               existing_comment='bcrypt digest. NULL for Google-only accounts',
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Stored lower-cased; compare against a lower-cased input',
               existing_nullable=False)
    op.alter_column('user_sessions', 'password_confirmed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When this session last re-proved the password. Per session, not per user',
               existing_nullable=True)
    op.alter_column('user_sessions', 'refresh_rotated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When the last rotation happened; bounds the grace window',
               existing_nullable=True)
    op.alter_column('user_sessions', 'previous_refresh_jti',
               existing_type=sa.VARCHAR(length=36),
               comment='Just-superseded token, honoured only inside the grace window',
               existing_nullable=True)
    op.alter_column('user_sessions', 'refresh_token_jti',
               existing_type=sa.VARCHAR(length=36),
               comment='The one refresh token currently valid for this session',
               existing_nullable=True)
    op.alter_column('user_sessions', 'revoked_reason',
               existing_type=sa.VARCHAR(length=50),
               comment='logout | password_change | password_reset | revoked_by_admin',
               existing_nullable=True)
    op.alter_column('user_sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment="Mirrors the refresh token's expiry; past this the session is dead",
               existing_nullable=False)
    op.alter_column('user_sessions', 'user_agent',
               existing_type=sa.TEXT(),
               comment='Untrusted self-reported text. Display only; never decide on it',
               existing_nullable=True)
    op.alter_column('user_sessions', 'ip_address',
               existing_type=sa.VARCHAR(length=45),
               comment='45 chars fits an IPv4-mapped IPv6 address',
               existing_nullable=True)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.VARCHAR(length=36),
               comment="The 'sid' claim in both the access and refresh tokens",
               existing_nullable=False)
    op.alter_column('user_invitations', 'note',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Optional message included in the email',
               existing_nullable=True)
    op.alter_column('user_invitations', 'role_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Role applied on acceptance',
               existing_nullable=True)
    op.alter_column('user_invitations', 'token',
               existing_type=sa.VARCHAR(length=128),
               comment=None,
               existing_comment='URL-safe random token from security.generate_token()',
               existing_nullable=False)
    op.alter_column('user_invitations', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment="Stored lower-cased; must match the accepting account's email",
               existing_nullable=False)
    op.alter_column('searchable_entities', 'route_param_field',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Which column fills the placeholder',
               existing_nullable=False,
               existing_server_default=sa.text("'id'::character varying"))
    op.alter_column('searchable_entities', 'subtitle_template',
               existing_type=sa.VARCHAR(length=191),
               comment=None,
               existing_comment="Second line, e.g. '{email}'",
               existing_nullable=True)
    op.alter_column('searchable_entities', 'display_template',
               existing_type=sa.VARCHAR(length=191),
               comment=None,
               existing_comment="Result title, e.g. '{first_name} {last_name}'",
               existing_nullable=False)
    op.alter_column('searchable_entities', 'icon',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='navIcons key. NULL renders no glyph',
               existing_nullable=True)
    op.alter_column('searchable_entities', 'group',
               existing_type=sa.VARCHAR(length=64),
               comment=None,
               existing_comment='Orders and buckets the result sections',
               existing_nullable=False)
    op.alter_column('searchable_entities', 'label',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Section heading in the results — 'Users'",
               existing_nullable=False)
    op.alter_column('search_logs', 'q',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='The raw query',
               existing_nullable=False)
    op.alter_column('roles', 'is_system',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Seeded role referenced by name in code; cannot be renamed or deleted',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('permissions', 'name',
               existing_type=sa.VARCHAR(length=150),
               comment=None,
               existing_comment="{resource}-{action}, resource singular, e.g. 'user-view'",
               existing_nullable=False)
    op.alter_column('permission_groups', 'module',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Owning module, e.g. 'core' or 'legacy'",
               existing_nullable=True)
    op.alter_column('permission_groups', 'display_order',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Ascending sort order in the permissions UI',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('permission_groups', 'name',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Slug, e.g. 'users'",
               existing_nullable=False)
    op.alter_column('partner_tiers', 'max_listings',
               existing_type=sa.INTEGER(),
               comment='NULL means unlimited. Not a -1 sentinel — see core/partner_tiers.py',
               existing_comment='NULL means unlimited. Not a -1 sentinel — see domain/partners/tiers.py',
               existing_nullable=True)
    op.alter_column('partner_tiers', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Stable code name, referenced from app/core/partner_tiers.py',
               existing_comment='Stable code name, referenced from app/domain/partners/tiers.py',
               existing_nullable=False)
    op.alter_column('error_occurrences', 'context',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               comment='User agent and referer ONLY. Never request input',
               existing_comment='User agent and referer ONLY. Never request input — see the class docstring',
               existing_nullable=True)
    op.alter_column('error_occurrences', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               comment=None,
               existing_comment='Who hit it, when there was a session. SET NULL — the sighting outlives the account',
               existing_nullable=True)
    op.alter_column('error_groups', 'occurrence_count',
               existing_type=sa.INTEGER(),
               comment='Denormalised. Occurrence rows are prunable; this count is not',
               existing_comment='Denormalised. Rows are pruned; this count is not',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('error_groups', 'latest_message',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment='Most recent message. Not part of the fingerprint',
               existing_nullable=False)
    op.alter_column('error_groups', 'module',
               existing_type=sa.VARCHAR(length=32),
               comment=None,
               existing_comment='Which part of the product raised it — filters the index',
               existing_nullable=False,
               existing_server_default=sa.text("'core'::character varying"))
    op.alter_column('error_groups', 'fingerprint',
               existing_type=sa.VARCHAR(length=32),
               comment='md5(exception_class|file|line|route). Excludes the message',
               existing_comment='md5(exception_class|file|line|route). Excludes the message — see the service',
               existing_nullable=False)
    op.alter_column('app_settings', 'favicon_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Cache key for the ?v= query and the ETag',
               existing_nullable=True)
    op.alter_column('app_settings', 'favicon_mime',
               existing_type=sa.VARCHAR(length=60),
               comment="Detected from the file's magic bytes, never from the request",
               existing_nullable=True)
    op.alter_column('app_settings', 'logo_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='Cache key for the ?v= query and the ETag',
               existing_nullable=True)
    op.alter_column('app_settings', 'logo_mime',
               existing_type=sa.VARCHAR(length=60),
               comment="Detected from the file's magic bytes, never from the request",
               existing_nullable=True)
    op.alter_column('api_credential_schemas', 'is_encrypted',
               existing_type=sa.BOOLEAN(),
               comment='Per field, not per credential — see the model',
               existing_nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('activity_log', 'batch_uuid',
               existing_type=sa.VARCHAR(length=36),
               comment='Groups the rows written by one bulk operation',
               existing_comment='Groups rows written by one logical operation, e.g. a bulk update',
               existing_nullable=True)
    op.alter_column('activity_log', 'causer_id',
               existing_type=sa.VARCHAR(length=36),
               comment='NULL when unauthenticated — a failed login has no causer',
               existing_comment='NULL for an unauthenticated actor — a failed login has no causer',
               existing_nullable=True)
    op.alter_column('activity_log', 'subject_id',
               existing_type=sa.VARCHAR(length=36),
               comment='String: ours are UUIDs, and role ids are integers',
               existing_comment='String because ours are UUIDs and role ids are ints; both fit',
               existing_nullable=True)
    op.alter_column('activity_log', 'subject_type',
               existing_type=sa.VARCHAR(length=100),
               comment="Model name: 'User' | 'Role'. Not a PHP namespace",
               existing_comment="Model name: 'User' | 'Role' — not a namespace",
               existing_nullable=True)
    op.alter_column('activity_log', 'description',
               existing_type=sa.TEXT(),
               comment=None,
               existing_comment="Human-readable summary, e.g. 'Ayush Mishra logged in'",
               existing_nullable=False)
