"""create the directory tables — categories, listings, enquiries

Punchlist tasks 1.1 through 1.7. `DIRECTORY_BUILD_PUNCHLIST.md` § 2.

⚠️ **This file was autogenerated and then cut back by hand, deliberately.**
`--autogenerate` also proposed around ninety operations against tables this
change does not touch: column comments across `users` and `user_sessions`, index
renames on `webhook_deliveries`, and — the dangerous ones — dropping the unique
constraints `permissions_name_key`, `roles_name_key` and
`permission_groups_name_key` in order to recreate them as unique indexes.

That is **pre-existing drift** between the models and the database, not part of
this change. Sweeping it in would have meant a migration whose name says
"directory tables" quietly rewriting the RBAC tables' constraints. It is left
alone and wants its own migration and its own testing.

**What this file actually does:** create eight tables and add two nullable
columns to `partners`. Nothing else.

Revision ID: 5098784d1c1c
Revises: c9a71f4e2b60
Create Date: 2026-08-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '5098784d1c1c'
down_revision: Union[str, None] = 'c9a71f4e2b60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('service_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=60), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('listing_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_service_categories_slug')
    )
    op.create_index(op.f('ix_service_categories_parent_id'), 'service_categories', ['parent_id'], unique=False)
    op.create_table('partner_expertise',
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('partner_id', 'category_id')
    )
    op.create_table('service_listings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('summary', sa.String(length=280), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('pricing_model', sa.Enum('FIXED', 'FROM', 'ON_REQUEST', name='listing_pricing_model'), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'REJECTED', name='listing_status'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['service_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_service_listings_slug')
    )
    op.create_index(op.f('ix_service_listings_partner_id'), 'service_listings', ['partner_id'], unique=False)
    op.create_index('ix_service_listings_partner_status', 'service_listings', ['partner_id', 'status'], unique=False)
    op.create_index(op.f('ix_service_listings_status'), 'service_listings', ['status'], unique=False)
    op.create_index('ix_service_listings_status_category', 'service_listings', ['status', 'category_id'], unique=False)
    op.create_table('enquiries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reference', sa.String(length=32), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=True),
    sa.Column('buyer_user_id', sa.String(length=36), nullable=True),
    sa.Column('buyer_name', sa.String(length=120), nullable=False),
    sa.Column('buyer_email', sa.String(length=255), nullable=False),
    sa.Column('buyer_phone', sa.String(length=30), nullable=True),
    sa.Column('company', sa.String(length=160), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('budget_range', sa.String(length=80), nullable=True),
    sa.Column('timeline', sa.String(length=80), nullable=True),
    sa.Column('source', sa.Enum('PROFILE', 'LISTING', name='enquiry_source'), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'RESPONDED', 'CLOSED', 'WON', 'LOST', name='enquiry_status'), nullable=False),
    sa.Column('first_responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['buyer_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['listing_id'], ['service_listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference', name='uq_enquiries_reference')
    )
    op.create_index('ix_enquiries_partner_created', 'enquiries', ['partner_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_enquiries_partner_id'), 'enquiries', ['partner_id'], unique=False)
    op.create_index('ix_enquiries_partner_responded', 'enquiries', ['partner_id', 'first_responded_at'], unique=False)
    op.create_index(op.f('ix_enquiries_status'), 'enquiries', ['status'], unique=False)
    op.create_table('listing_attributes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=300), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['service_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_attributes_listing_id'), 'listing_attributes', ['listing_id'], unique=False)
    op.create_table('listing_media',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('alt_text', sa.String(length=200), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['service_listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_media_listing_id'), 'listing_media', ['listing_id'], unique=False)
    op.create_table('enquiry_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enquiry_id', sa.String(length=36), nullable=False),
    sa.Column('direction', sa.Enum('FROM_BUYER', 'FROM_PARTNER', name='enquiry_message_direction'), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enquiry_messages_enquiry_id'), 'enquiry_messages', ['enquiry_id'], unique=False)
    op.create_table('enquiry_recipients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('enquiry_id', sa.String(length=36), nullable=False),
    sa.Column('partner_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('enquiry_id', 'partner_id', name='uq_enquiry_recipient')
    )
    op.create_index(op.f('ix_enquiry_recipients_enquiry_id'), 'enquiry_recipients', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_enquiry_recipients_partner_id'), 'enquiry_recipients', ['partner_id'], unique=False)

    # --- punchlist 1.2: the public half of a partner ---------------------
    op.add_column('partners', sa.Column('service_areas', sa.Text(), nullable=True, comment='Comma-separated display list of served areas. Display only, never filtered on'))
    op.add_column('partners', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))


def downgrade() -> None:
    """Drop everything this created, children before parents.

    The order is not simply the reverse of `upgrade()`: `service_categories` is
    referenced by `service_listings` with RESTRICT, so dropping the taxonomy
    before the listings pointing at it fails.

    Dropping a table takes its indexes with it, so those are not listed
    individually. The two `partners` columns are removed explicitly because that
    table survives.

    ⚠️ **The enum types must be dropped too.** Postgres keeps a type after the
    table using it is gone, so without this a re-upgrade fails with "type
    already exists" — which is exactly the failure that makes a downgrade look
    like it worked until somebody tries to go forward again.
    """
    op.drop_column('partners', 'published_at')
    op.drop_column('partners', 'service_areas')

    op.drop_table('enquiry_recipients')
    op.drop_table('enquiry_messages')
    op.drop_table('enquiries')
    op.drop_table('listing_media')
    op.drop_table('listing_attributes')
    op.drop_table('service_listings')
    op.drop_table('partner_expertise')
    op.drop_table('service_categories')

    for enum_name in (
        'listing_status',
        'listing_pricing_model',
        'enquiry_source',
        'enquiry_status',
        'enquiry_message_direction',
    ):
        op.execute(f'DROP TYPE IF EXISTS {enum_name}')
