"""fix_failed_login_attempts_to_integer

Revision ID: a1ebf7c66c45
Revises: 003f7590e39b
Create Date: 2026-04-16 17:10:27.351654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ebf7c66c45'
down_revision: Union[str, None] = '003f7590e39b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'failed_login_attempts',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Integer(),
               postgresql_using='failed_login_attempts::integer',
               existing_comment='Consecutive failed sign-in attempts; reset on success',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_users', 'failed_login_attempts',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=10),
               existing_comment='Consecutive failed sign-in attempts; reset on success',
               existing_nullable=False)
    # ### end Alembic commands ###
