"""create partners and partner_tiers, link users.partner_id

Revision ID: a9f2c71e5b64
Revises: 5a3a6159bbda
Create Date: 2026-08-10

Phase 1 of `documentation/planning/PARTNER_DIRECTORY_PLAN.md`, whose § 11 build
sequence puts the organisation layer first because everything partner-owned
carries `partner_id` and retrofitting it later means backfilling ownership on
every table.

**Hand-written, not autogenerated.** The same pre-existing model/database drift
that forced `5a3a6159bbda` to be hand-trimmed is still present — autogenerate
emits ~84 unrelated `alter_column` operations against `activity_log`,
`app_settings`, `permissions`, `permission_groups` and `users`. That drift is
real and deserves a migration of its own; it is not this one.

Order is load-bearing: `partner_tiers` before `partners` (FK), `partners` before
`users.partner_id` (FK).

`users.partner_id` is nullable and that is permanent, not a migration
convenience — **NULL means Leapswitch staff**. It is the single column every
scoping rule reads.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a9f2c71e5b64"
down_revision: str | None = "5a3a6159bbda"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "partner_tiers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name",
            sa.String(length=50),
            nullable=False,
            comment="Stable code name, referenced from app/core/partner_tiers.py",
        ),
        sa.Column("display_name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "max_listings",
            sa.Integer(),
            nullable=True,
            comment="NULL means unlimited. Not a -1 sentinel — see core/partner_tiers.py",
        ),
        sa.Column(
            "featured_slots",
            sa.Integer(),
            nullable=False,
            server_default="0",
            comment="Concurrent featured listings. 0 means featured placement is unavailable",
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
            comment="An inactive tier keeps its partners but cannot be assigned to new ones",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_partner_tiers_name"), "partner_tiers", ["name"], unique=True
    )

    op.create_table(
        "partners",
        sa.Column("id", sa.String(length=36), nullable=False),
        # --- Identity -------------------------------------------------------
        sa.Column(
            "name",
            sa.String(length=255),
            nullable=False,
            comment="Trading name, shown everywhere in the UI",
        ),
        sa.Column(
            "legal_name",
            sa.String(length=255),
            nullable=True,
            comment="Registered name, for documents",
        ),
        sa.Column(
            "slug",
            sa.String(length=120),
            nullable=False,
            comment="Stable public key — /partners/<slug>. Never reuse across partners",
        ),
        sa.Column("tier_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACTIVE", "SUSPENDED", name="partner_status"),
            nullable=False,
            server_default="PENDING",
            comment="Gates LOGIN for every user in this organisation. Not visibility",
        ),
        # --- Directory face -------------------------------------------------
        sa.Column(
            "tagline",
            sa.String(length=200),
            nullable=True,
            comment="One line under the name on the listing page",
        ),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("logo_path", sa.String(length=255), nullable=True),
        sa.Column("banner_path", sa.String(length=255), nullable=True),
        sa.Column("website", sa.String(length=255), nullable=True),
        sa.Column(
            "public_email",
            sa.String(length=255),
            nullable=True,
            comment="Shown publicly. NOT a login — see users.email",
        ),
        sa.Column("public_phone", sa.String(length=30), nullable=True),
        sa.Column("founded_year", sa.Integer(), nullable=True),
        sa.Column(
            "employee_range",
            sa.String(length=50),
            nullable=True,
            comment="Buyer filter, e.g. '11-50'",
        ),
        sa.Column(
            "verification_level",
            sa.Enum(
                "UNVERIFIED",
                "VERIFIED",
                "PREMIER",
                name="partner_verification_level",
            ),
            nullable=False,
            server_default="UNVERIFIED",
            comment="What Leapswitch vouches for. Ranked BEFORE any paid placement",
        ),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verified_by",
            sa.String(length=36),
            nullable=True,
            comment="Which staff member vouched. Null once that account is deleted",
        ),
        sa.Column(
            "is_listed",
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
            comment="Publicly visible in the directory. Independent of `status`",
        ),
        # --- Commercial / compliance ----------------------------------------
        sa.Column("gst_number", sa.String(length=30), nullable=True),
        sa.Column("pan_number", sa.String(length=30), nullable=True),
        sa.Column("billing_address", sa.Text(), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("state", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("agreement_signed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "onboarded_by",
            sa.String(length=36),
            nullable=True,
            comment="Which staff member onboarded this partner",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="INTERNAL ONLY — never serialise this into a partner-facing schema",
        ),
        # --- Audit ----------------------------------------------------------
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        # SET NULL on the tier: deleting a tier must never delete the partners on
        # it. A tier-less partner falls back to the most restrictive entitlement.
        sa.ForeignKeyConstraint(["tier_id"], ["partner_tiers.id"], ondelete="SET NULL"),
        # SET NULL on every user reference: a partner outlives the staff member
        # who onboarded, verified or last edited it.
        sa.ForeignKeyConstraint(["verified_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["onboarded_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_partners_name"), "partners", ["name"])
    op.create_index(op.f("ix_partners_slug"), "partners", ["slug"], unique=True)
    op.create_index(op.f("ix_partners_status"), "partners", ["status"])
    op.create_index(op.f("ix_partners_tier_id"), "partners", ["tier_id"])
    op.create_index(op.f("ix_partners_is_listed"), "partners", ["is_listed"])
    op.create_index(
        op.f("ix_partners_verification_level"), "partners", ["verification_level"]
    )

    op.add_column(
        "users",
        sa.Column(
            "partner_id",
            sa.String(length=36),
            nullable=True,
            comment="Organisation membership. NULL means Leapswitch staff",
        ),
    )
    op.create_index(op.f("ix_users_partner_id"), "users", ["partner_id"])
    # SET NULL, not CASCADE: deleting a partner organisation must not delete the
    # people in it, or the audit trail referencing them would go with it.
    op.create_foreign_key(
        "fk_users_partner_id",
        "users",
        "partners",
        ["partner_id"],
        ["id"],
        ondelete="SET NULL",
    )

    # `users.company_name` is now redundant with this link and is left in place
    # deliberately — it holds free text typed at self-registration, before any
    # organisation exists to point at. Reconciling the two is a data question,
    # not a schema one, and belongs with the partner self-signup flow.


def downgrade() -> None:
    op.drop_constraint("fk_users_partner_id", "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_partner_id"), table_name="users")
    op.drop_column("users", "partner_id")

    op.drop_index(op.f("ix_partners_verification_level"), table_name="partners")
    op.drop_index(op.f("ix_partners_is_listed"), table_name="partners")
    op.drop_index(op.f("ix_partners_tier_id"), table_name="partners")
    op.drop_index(op.f("ix_partners_status"), table_name="partners")
    op.drop_index(op.f("ix_partners_slug"), table_name="partners")
    op.drop_index(op.f("ix_partners_name"), table_name="partners")
    op.drop_table("partners")

    op.drop_index(op.f("ix_partner_tiers_name"), table_name="partner_tiers")
    op.drop_table("partner_tiers")

    # PostgreSQL does not drop an enum with the table that created it, so a
    # downgrade-then-upgrade would fail on "type already exists" without this —
    # the same footnote as 5a3a6159bbda.
    sa.Enum(name="partner_verification_level").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="partner_status").drop(op.get_bind(), checkfirst=True)
