"""drop inherited test-platform tables

The logic-test product this scaffold came from is being retired: the owner
confirmed on 2026-08-06 that none of Test Platform, Candidate, Create, Add
Category, Add Job Role, Add Test Section, Select Question Type or Add Question
serve the marketplace. This drops the tables that belonged solely to it, and the
RBAC rows that gated them.

**Written by hand, not autogenerated.** `SCAFFOLD_CLEANUP_PLAN.md` § 3.1 is
explicit that autogenerate emits drops in arbitrary order, which fails on foreign
keys. The order below is reverse-dependency, verified against
`information_schema` rather than assumed:

    session_answers ─┬─> questions ──> tests
                     └─> test_sessions ──> tests
    options ─────────> questions
    candidates        (no foreign keys)
    categories        (no foreign keys — nothing ever referenced it, so the
                       "questions might depend on it" worry was unfounded)

`tests` and `test_sessions` also point at `users`, which stays.

Revision ID: c1e70a5d94b2
Revises: f5a3c81b7d29
Create Date: 2026-08-06
"""

from alembic import op

revision = "c1e70a5d94b2"
down_revision = "f5a3c81b7d29"
branch_labels = None
depends_on = None


#: Reverse-dependency order. Children before parents — reversing this list drops
#: `tests` first and fails on `questions_test_id_fkey`.
TABLES = [
    "session_answers",
    "options",
    "test_sessions",
    "questions",
    "tests",
    "candidates",
    "categories",
]

#: The RBAC rows that gated the retired endpoints. Removed from
#: `app/core/permissions.py` in the same change, so the seeder would otherwise
#: leave them orphaned in the database forever — the seeder only adds and
#: updates, it never prunes.
DEAD_PERMISSION_PREFIXES = ("category-", "candidate-")

DEAD_PERMISSION_GROUPS = ("categories", "candidates")


def upgrade() -> None:
    # Role grants first: role_permissions.permission_id is a foreign key onto
    # permissions, so deleting the permissions first would fail.
    for prefix in DEAD_PERMISSION_PREFIXES:
        op.execute(
            "DELETE FROM role_permissions WHERE permission_id IN "
            f"(SELECT id FROM permissions WHERE name LIKE '{prefix}%')"
        )
        op.execute(f"DELETE FROM permissions WHERE name LIKE '{prefix}%'")

    for group in DEAD_PERMISSION_GROUPS:
        op.execute(f"DELETE FROM permission_groups WHERE name = '{group}'")

    for table in TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table} CASCADE")


def downgrade() -> None:
    """Not reversible, deliberately.

    Recreating seven tables, their indexes, their foreign keys and the RBAC rows
    would be a large amount of code that reconstructs a **retired product** — and
    it could never restore the data, which is the only part anyone would actually
    want back. `DATABASE_MIGRATIONS.md` § 6 sanctions raising here instead.

    To go back, restore the pre-migration dump taken as part of running this
    (`SCAFFOLD_CLEANUP_PLAN.md` § 3.1 requires one) and stamp the previous
    revision.
    """
    raise NotImplementedError(
        "Irreversible: the inherited test-platform tables were dropped as part of "
        "retiring that product. Restore from the pre-migration backup and "
        "`alembic stamp f5a3c81b7d29`."
    )
