"""Add users.theme_preference — a personal theme override.

Revision ID: c1f7a03b5e42
Revises: d4a71b93c8e2
Create Date: 2026-08-20

Additive and **not backfilled**. Every existing user starts NULL, which means
"inherit the installation's theme" — exactly what they render today, so this
migration changes nothing anyone sees until they choose.

There is deliberately **no server default**. A default would make "never chose"
indistinguishable from "deliberately chose the theme that happens to be the
current default", and those two must stay different: an administrator rebranding
the installation has to reach the first group and must not override the second.

Hand-written rather than autogenerated. The only change is one nullable column, so
there is nothing for the autogenerate diff to get wrong and nothing to review that
this file does not state.
"""

from alembic import op
import sqlalchemy as sa

revision = "c1f7a03b5e42"
down_revision = "d4a71b93c8e2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.add_column(
        "users",
        sa.Column(
            "theme_preference",
            sa.String(length=40),
            nullable=True,
            comment="Key into core.theme.THEME_PRESETS; NULL inherits app_settings",
        ),
    )


def downgrade() -> None:
    op.drop_column("users", "theme_preference")
