"""create the settings registry

Revision ID: c4e1a9038d72
Revises: b3d7e02f4c19
Create Date: 2026-08-11

LeapDesk parity Module 11 — Configuration. Columns match `settings` in the
reference one for one, including the `(module, group)` index, because that pair
is the screen's sort and filter key and the index exists for the same reason
theirs does: the page orders by it on every load.

**Hand-written, not autogenerated.** The same pre-existing model/database drift
that forced `5a3a6159bbda` and `a9f2c71e5b64` to be hand-trimmed is still there —
autogenerate emits ~84 unrelated `alter_column` operations against
`activity_log`, `app_settings`, `permissions`, `permission_groups` and `users`.
That drift is real and deserves a migration of its own; it is not this one.

**`value` is JSONB, not JSON.** Postgres can index and compare JSONB, and the
first question anyone asks of a settings table is "which of these are still on
their defaults" — which is a comparison. The cost is that JSONB does not preserve
key order or duplicate keys, neither of which a setting value should rely on.

**No rows are inserted here.** The registry is seeded by
`app/db/seed_settings.py`, which is idempotent and runs on every deploy. Putting
the rows in the migration would freeze their labels and descriptions at the
moment it was written — and those are exactly the fields that get improved later.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c4e1a9038d72"
down_revision: str | None = "b3d7e02f4c19"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "key", sa.String(length=150), nullable=False,
            comment="Dotted, namespaced — 'security.reauth.window_minutes'. The API contract",
        ),
        sa.Column(
            "value", postgresql.JSONB(astext_type=sa.Text()), nullable=True,
            comment="Always {'v': <typed value>}. See the note on null-vs-unset",
        ),
        sa.Column(
            "type", sa.String(length=20), server_default="string", nullable=False,
            comment="bool | int | string | text | json — see core/setting_types.py",
        ),
        sa.Column(
            "group", sa.String(length=64), nullable=False,
            comment="Card heading on the screen — 'Queue Monitor', 'Invitations'",
        ),
        sa.Column(
            "module", sa.String(length=32), server_default="core", nullable=False,
            comment="Which part of the product owns this. Filters the index",
        ),
        sa.Column(
            "label", sa.String(length=191), nullable=False,
            comment="What the admin sees. A sentence, not the key",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True,
            comment="One line explaining the consequence of changing it",
        ),
        sa.Column(
            "updated_by", sa.String(length=36), nullable=True,
            comment="Who last changed it. SET NULL — the change outlives the account",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_settings_key"),
    )
    op.create_index(op.f("ix_settings_group"), "settings", ["group"])
    op.create_index(op.f("ix_settings_module"), "settings", ["module"])
    op.create_index("ix_settings_module_group", "settings", ["module", "group"])


def downgrade() -> None:
    op.drop_index("ix_settings_module_group", table_name="settings")
    op.drop_index(op.f("ix_settings_module"), table_name="settings")
    op.drop_index(op.f("ix_settings_group"), table_name="settings")
    op.drop_table("settings")
