"""create agent_conversations, agent_conversation_messages and ai_message_feedback

Revision ID: c4e91b73a208
Revises: b6d41e807f92
Create Date: 2026-08-12

LeapDesk parity Module 9 — AI Assistant. Column names match the reference's
`Laravel\\Ai` tables so the two schemas read the same; where a *type* differs it
is documented on `app/models/ai_conversation.py`, not here.

**Hand-written, not autogenerated** — the pre-existing model/database drift makes
`--autogenerate` emit dozens of unrelated `alter_column` operations against other
tables, which is how an unrelated column gets silently altered by a migration
nobody read to the end.

**`ai_message_feedback.conversation_id` has no foreign key**, matching the
reference and for the same reason `search_logs.user_id` has none: feedback on a
thread that is later deleted is still a data point about answer quality, and a
cascade would delete the negative feedback at exactly the moment someone clears
the conversation that produced it.

Nothing is seeded. The assistant stays off until an administrator adds an
Anthropic key and enables it in API Credentials.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c4e91b73a208"
down_revision: str | None = "b6d41e807f92"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "agent_conversations",
        sa.Column("id", sa.String(length=36), primary_key=True),
        # SET NULL, not CASCADE: the thread records what the assistant was asked
        # and what it answered, and that outlives the account that asked.
        sa.Column(
            "user_id",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("title", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "agent_conversations_user_updated_index",
        "agent_conversations",
        ["user_id", "updated_at"],
    )

    op.create_table(
        "agent_conversation_messages",
        sa.Column("id", sa.String(length=36), primary_key=True),
        # CASCADE here and only here: a message has no meaning without its
        # thread, where a thread has meaning without its author.
        sa.Column(
            "conversation_id",
            sa.String(length=36),
            sa.ForeignKey("agent_conversations.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("agent", sa.String(length=100), nullable=True),
        sa.Column("role", sa.String(length=25), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        # JSONB rather than the reference's text columns — queryable, which is
        # what makes "how often was database_query called" answerable in SQL.
        sa.Column("attachments", postgresql.JSONB(), nullable=True),
        sa.Column("tool_calls", postgresql.JSONB(), nullable=True),
        sa.Column("tool_results", postgresql.JSONB(), nullable=True),
        sa.Column("usage", postgresql.JSONB(), nullable=True),
        sa.Column("meta", postgresql.JSONB(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_agent_conversation_messages_conversation_id",
        "agent_conversation_messages",
        ["conversation_id"],
    )
    op.create_index(
        "agent_messages_conversation_user_updated_index",
        "agent_conversation_messages",
        ["conversation_id", "user_id", "updated_at"],
    )

    op.create_table(
        "ai_message_feedback",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("conversation_id", sa.String(length=36), nullable=True),
        sa.Column(
            "user_id",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("helpful", sa.Boolean(), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_ai_message_feedback_conversation_id",
        "ai_message_feedback",
        ["conversation_id"],
    )


def downgrade() -> None:
    op.drop_index("ix_ai_message_feedback_conversation_id", table_name="ai_message_feedback")
    op.drop_table("ai_message_feedback")
    op.drop_index(
        "agent_messages_conversation_user_updated_index",
        table_name="agent_conversation_messages",
    )
    op.drop_index(
        "ix_agent_conversation_messages_conversation_id",
        table_name="agent_conversation_messages",
    )
    op.drop_table("agent_conversation_messages")
    op.drop_index(
        "agent_conversations_user_updated_index", table_name="agent_conversations"
    )
    op.drop_table("agent_conversations")
