"""Change password_hash to password

Revision ID: cc12bb0fb8fb
Revises: d9e3f1a2b4c5
Create Date: 2026-04-19 14:29:50.795857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc12bb0fb8fb'
down_revision: Union[str, None] = 'd9e3f1a2b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add password column as nullable first
    op.add_column('admin_users', sa.Column('password', sa.String(length=255), nullable=True, comment='plain text password (dev/test only)'))
    # Copy data from password_hash to password
    op.execute('UPDATE admin_users SET password = password_hash WHERE password IS NULL')
    # Drop the old password_hash column
    op.drop_column('admin_users', 'password_hash')
    # Make password NOT NULL
    op.alter_column('admin_users', 'password', existing_type=sa.String(length=255), nullable=False)
    
    op.drop_constraint('candidates_email_key', 'candidates', type_='unique')
    
    # Same process for users table
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=True, comment='plain text password (dev/test only)'))
    op.execute('UPDATE users SET password = password_hash WHERE password IS NULL')
    op.drop_column('users', 'password_hash')
    op.alter_column('users', 'password', existing_type=sa.String(length=255), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    op.create_unique_constraint('candidates_email_key', 'candidates', ['email'])
    op.add_column('admin_users', sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='bcrypt hash of the admin password'))
    op.drop_column('admin_users', 'password')
    # ### end Alembic commands ###
