"""create feature_flags

Revision ID: d18b60c4a3f5
Revises: c4e1a9038d72
Create Date: 2026-08-11

LeapDesk parity Module 13 — Feature Flags. Columns match one for one.

Written **ahead of** the service, router and screen so that work can proceed in
parallel without a second author touching the Alembic chain: two migrations that
both revise `c4e1a9038d72` produce two heads, and Alembic does not complain until
someone runs `upgrade`, long after both authors believe they are finished.

**Hand-written, not autogenerated**, for the same reason as `c4e1a9038d72` — the
pre-existing model/database drift makes `--autogenerate` emit ~84 unrelated
`alter_column` operations against five other tables.

**`target_roles` and `target_user_ids` are JSONB arrays, both nullable.** NULL and
`[]` mean the same thing — no restriction on that axis — and the model treats them
identically rather than defining a distinction nobody would remember.

**No rows are seeded.** A flag exists because some code branches on it; seeding
one that nothing reads would put a switch on screen that does nothing.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "d18b60c4a3f5"
down_revision: str | None = "c4e1a9038d72"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "key", sa.String(length=150), nullable=False,
            comment="What the code checks — 'partner.self_serve_listings'",
        ),
        sa.Column(
            "name", sa.String(length=191), nullable=False,
            comment="Human name for the screen. The key is not it",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True,
            comment="What turning this on actually does",
        ),
        sa.Column(
            "enabled", sa.Boolean(), server_default=sa.false(), nullable=False,
            comment="Master switch. Off means off for everyone, targets ignored",
        ),
        sa.Column(
            "target_roles", postgresql.JSONB(astext_type=sa.Text()), nullable=True,
            comment="Role names this is on for. NULL/[] means no role restriction",
        ),
        sa.Column(
            "target_user_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=True,
            comment="User ids this is on for. NULL/[] means no user restriction",
        ),
        sa.Column(
            "updated_by", sa.String(length=36), nullable=True,
            comment="Who last changed it. SET NULL — the change outlives the account",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key", name="uq_feature_flags_key"),
    )
    op.create_index(op.f("ix_feature_flags_enabled"), "feature_flags", ["enabled"])


def downgrade() -> None:
    op.drop_index(op.f("ix_feature_flags_enabled"), table_name="feature_flags")
    op.drop_table("feature_flags")
