"""create api_consumers, api_consumer_tokens and api_request_logs

Revision ID: d2f60a91c7e4
Revises: c4e91b73a208
Create Date: 2026-08-12

LeapDesk parity Module 10 Part I — the governance surface for machine identities.
Part II, its registry-driven read engine, is deliberately not ported: it answers
a question we do not have, and the reference's own code review found 100 of its
105 registered resources had no field allowlist (NULL meaning *every column*).

**Hand-written, not autogenerated** — the pre-existing model/database drift makes
`--autogenerate` emit dozens of unrelated `alter_column` operations.

Three column decisions are load-bearing and are argued in full on
`app/models/api_consumer.py`:

* `api_consumer_tokens.token_hash` is **SHA-256 and unique-indexed**, not bcrypt.
  A salted hash could not be looked up, so every API call would scan every row.
* `consumer_id` CASCADEs on the token, `created_by` is SET NULL. The credential
  dies with its system; the record of who issued it outlives whoever issued it.
* `api_request_logs.consumer_id` has **no foreign key** — a rejected call may name
  no valid consumer, and a deleted consumer's traffic is exactly what someone
  investigating that deletion needs.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d2f60a91c7e4"
down_revision: str | None = "c4e91b73a208"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "api_consumers",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=150), nullable=False, unique=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("owner_name", sa.String(length=150), nullable=True),
        # Nullable in the column, required by the schema — see the model.
        sa.Column("owner_email", sa.String(length=255), nullable=True),
        # The kill switch. Outranks any token the consumer holds.
        sa.Column("active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column(
            "created_by",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column(
            "updated_by",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )

    op.create_table(
        "api_consumer_tokens",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "consumer_id",
            sa.String(length=36),
            sa.ForeignKey("api_consumers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False, unique=True),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column(
            "abilities",
            sa.ARRAY(sa.String(length=100)),
            nullable=False,
            server_default="{}",
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_by",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_api_consumer_tokens_consumer_id", "api_consumer_tokens", ["consumer_id"]
    )

    op.create_table(
        "api_request_logs",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("consumer_id", sa.String(length=36), nullable=True),
        sa.Column("token_id", sa.String(length=36), nullable=True),
        sa.Column("token_prefix", sa.String(length=16), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=False),
        sa.Column("path", sa.String(length=500), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("outcome", sa.String(length=50), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_api_request_logs_consumer_id", "api_request_logs", ["consumer_id"])
    op.create_index(
        "api_request_logs_consumer_created_index",
        "api_request_logs",
        ["consumer_id", "created_at"],
    )
    # Retention deletes by age, so the index it needs is on age alone.
    op.create_index("api_request_logs_created_index", "api_request_logs", ["created_at"])


def downgrade() -> None:
    op.drop_index("api_request_logs_created_index", table_name="api_request_logs")
    op.drop_index("api_request_logs_consumer_created_index", table_name="api_request_logs")
    op.drop_index("ix_api_request_logs_consumer_id", table_name="api_request_logs")
    op.drop_table("api_request_logs")
    op.drop_index("ix_api_consumer_tokens_consumer_id", table_name="api_consumer_tokens")
    op.drop_table("api_consumer_tokens")
    op.drop_table("api_consumers")
