"""create searchable_entities and search_logs

Revision ID: e5c2f71a94b8
Revises: d18b60c4a3f5
Create Date: 2026-08-11

LeapDesk parity Module 8 — Global Search. Column names match the reference so
the two schemas read the same; two columns mean something different in our stack
and the difference is documented on the model, not here.

Written **ahead of** the service, router and screen so that work can proceed in
parallel without a second author touching the Alembic chain — two migrations that
both revise the same head produce two heads, and Alembic does not complain until
someone runs `upgrade`.

**Hand-written, not autogenerated** — the pre-existing model/database drift makes
`--autogenerate` emit ~84 unrelated `alter_column` operations against five other
tables.

**`search_logs.user_id` has no foreign key**, deliberately, and it is the same
call `activity_log.causer_id` already makes: the log outlives the account. A
cascade would delete the evidence of what someone searched for at the moment
their account was removed, which is the one moment it is most likely to matter.

**No rows are seeded.** Which record types are searchable is an administrator's
decision, and seeding `User` would be deciding it for them.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e5c2f71a94b8"
down_revision: str | None = "d18b60c4a3f5"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "searchable_entities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "model_class", sa.String(length=150), nullable=False,
            comment="Model NAME resolved against an allowlist in code — never imported directly",
        ),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("group", sa.String(length=64), nullable=False),
        sa.Column("icon", sa.String(length=50), nullable=True),
        sa.Column(
            "fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False,
            comment="Column names to search. Checked against the model, never trusted",
        ),
        sa.Column("display_template", sa.String(length=191), nullable=False),
        sa.Column("subtitle_template", sa.String(length=191), nullable=True),
        sa.Column(
            "route_name", sa.String(length=191), nullable=False,
            comment="Path template with one placeholder, e.g. '/dashboard/users/{id}'",
        ),
        sa.Column(
            "route_param_field", sa.String(length=64), server_default="id", nullable=False,
        ),
        sa.Column(
            "permission", sa.String(length=100), nullable=True,
            comment="Required permission. NULL = any signed-in user. NOT row scoping",
        ),
        sa.Column("enabled", sa.Boolean(), server_default=sa.true(), nullable=False),
        sa.Column("sort_order", sa.Integer(), server_default="0", nullable=False),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("model_class", name="uq_searchable_entities_model_class"),
    )
    op.create_index(
        "ix_searchable_entities_enabled_order", "searchable_entities", ["enabled", "sort_order"]
    )

    op.create_table(
        "search_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "user_id", sa.String(length=36), nullable=True,
            comment="No FK — the log outlives the account, like activity_log.causer_id",
        ),
        sa.Column("q", sa.String(length=255), nullable=False),
        sa.Column("result_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("duration_ms", sa.Integer(), server_default="0", nullable=False),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_logs_user_id"), "search_logs", ["user_id"])
    op.create_index(op.f("ix_search_logs_created_at"), "search_logs", ["created_at"])
    op.create_index("ix_search_logs_user_time", "search_logs", ["user_id", "created_at"])


def downgrade() -> None:
    op.drop_index("ix_search_logs_user_time", table_name="search_logs")
    op.drop_index(op.f("ix_search_logs_created_at"), table_name="search_logs")
    op.drop_index(op.f("ix_search_logs_user_id"), table_name="search_logs")
    op.drop_table("search_logs")
    op.drop_index("ix_searchable_entities_enabled_order", table_name="searchable_entities")
    op.drop_table("searchable_entities")
