"""unify accounts into users and add RBAC

Folds `admin_users` into `users`, hashes every existing plaintext password, and
introduces roles / permissions / permission_groups / invitations.

Hand-written, NOT autogenerated: the order matters, three enum types have to be
created before the columns that use them, and the account fold is a data
migration that autogenerate cannot express.

Sequence:
  1. create the new enum types
  2. create the RBAC tables and seed the system ROLE ROWS (names only — the
     seeder fills in permissions afterwards, idempotently)
  3. widen `users` with every new column
  4. backfill `users`: split `name`, lower-case emails, HASH the plaintext
     passwords, set status/account_type
  5. copy `admin_users` rows into `users`, PRESERVING their ids so
     `tests.created_by` stays valid
  6. assign roles: migrated admins -> Admin/SuperAdmin, pre-existing users -> User
  7. repoint `tests.created_by` at `users`, drop `admin_users`, drop the old
     `users.role` and `name` columns and the two dead enum types

Revision ID: e7b41c9a2d10
Revises: 3ab496a7c5b7
"""

import uuid
from datetime import datetime, timezone
from typing import Sequence, Union

import bcrypt
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e7b41c9a2d10"
down_revision: Union[str, None] = "3ab496a7c5b7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


BCRYPT_ROUNDS = 12

# Role names must match app.core.permissions. Duplicated here on purpose: a
# migration is a snapshot and must not drift when the constants are edited.
ROLE_ROOT = "RootUser"
ROLE_SUPER_ADMIN = "SuperAdmin"
ROLE_ADMIN = "Admin"
ROLE_STAFF = "Staff"
ROLE_PARTNER = "Partner"
ROLE_USER = "User"
SYSTEM_ROLES = [
    ROLE_ROOT,
    ROLE_SUPER_ADMIN,
    ROLE_ADMIN,
    ROLE_STAFF,
    ROLE_PARTNER,
    ROLE_USER,
]

user_status = postgresql.ENUM(
    "INACTIVE", "ACTIVE", "SUSPENDED", name="user_status", create_type=False
)
account_type = postgresql.ENUM("staff", "partner", name="account_type", create_type=False)
auth_provider = postgresql.ENUM(
    "credentials", "google", name="auth_provider", create_type=False
)
invitation_status = postgresql.ENUM(
    "pending", "accepted", "expired", "cancelled", name="invitation_status", create_type=False
)
invitation_account_type = postgresql.ENUM(
    "staff", "partner", name="invitation_account_type", create_type=False
)


def _hash(plain: str | None) -> str | None:
    """bcrypt a plaintext password. Returns None when there is nothing to hash."""
    if not plain:
        return None
    return bcrypt.hashpw(
        plain.encode("utf-8")[:72], bcrypt.gensalt(rounds=BCRYPT_ROUNDS)
    ).decode("utf-8")


def upgrade() -> None:
    bind = op.get_bind()
    now = datetime.now(timezone.utc)

    # ---------------------------------------------------------------- 1. enums
    for enum in (
        user_status,
        account_type,
        auth_provider,
        invitation_status,
        invitation_account_type,
    ):
        enum.create(bind, checkfirst=True)

    # --------------------------------------------------------- 2. RBAC tables
    op.create_table(
        "permission_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("module", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_permission_groups_name"), "permission_groups", ["name"])

    op.create_table(
        "permissions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=200), nullable=False),
        sa.Column("permission_group_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["permission_group_id"], ["permission_groups.id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_permissions_name"), "permissions", ["name"])
    op.create_index(
        op.f("ix_permissions_permission_group_id"), "permissions", ["permission_group_id"]
    )

    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_system", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_roles_name"), "roles", ["name"])

    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["permission_id"], ["permissions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("role_id", "permission_id"),
    )

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )

    op.create_table(
        "user_invitations",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column("status", invitation_status, nullable=False, server_default="pending"),
        sa.Column(
            "account_type", invitation_account_type, nullable=False, server_default="partner"
        ),
        sa.Column("role_id", sa.Integer(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("invited_by", sa.String(length=36), nullable=True),
        sa.Column("accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("accepted_user_id", sa.String(length=36), nullable=True),
        sa.Column("resent_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["invited_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["accepted_user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("token"),
    )
    op.create_index(op.f("ix_user_invitations_email"), "user_invitations", ["email"])
    op.create_index(op.f("ix_user_invitations_token"), "user_invitations", ["token"])
    op.create_index(op.f("ix_user_invitations_status"), "user_invitations", ["status"])

    # Seed the system role rows so step 6 has something to assign. Permissions
    # are attached by app/db/seed_rbac.py, which is idempotent.
    for name in SYSTEM_ROLES:
        bind.execute(
            sa.text(
                "INSERT INTO roles (name, display_name, is_system, created_at, updated_at) "
                "VALUES (:name, :name, true, :now, :now) ON CONFLICT (name) DO NOTHING"
            ),
            {"name": name, "now": now},
        )

    # ------------------------------------------------------ 3. widen `users`
    op.add_column("users", sa.Column("first_name", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("last_name", sa.String(length=100), nullable=True))
    op.add_column("users", sa.Column("designation", sa.String(length=150), nullable=True))
    op.add_column("users", sa.Column("employee_id", sa.String(length=50), nullable=True))
    op.add_column("users", sa.Column("phone", sa.String(length=30), nullable=True))
    op.add_column("users", sa.Column("company_name", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("google_id", sa.String(length=255), nullable=True))
    op.add_column("users", sa.Column("google_avatar", sa.String(length=500), nullable=True))
    op.add_column(
        "users", sa.Column("email_verified_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("auth_provider", auth_provider, nullable=False, server_default="credentials"),
    )
    op.add_column(
        "users",
        sa.Column("account_type", account_type, nullable=False, server_default="partner"),
    )
    op.add_column(
        "users", sa.Column("status", user_status, nullable=False, server_default="INACTIVE")
    )
    op.add_column(
        "users",
        sa.Column(
            "timezone_preference",
            sa.String(length=50),
            nullable=False,
            server_default="Asia/Kolkata",
        ),
    )
    op.add_column(
        "users",
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column("users", sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True))
    op.add_column("users", sa.Column("last_login_ip", sa.String(length=45), nullable=True))
    op.add_column("users", sa.Column("password_reset_token", sa.Text(), nullable=True))
    op.add_column(
        "users", sa.Column("password_reset_expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("users", sa.Column("created_by", sa.String(length=36), nullable=True))
    op.add_column("users", sa.Column("updated_by", sa.String(length=36), nullable=True))

    # Google-only accounts have no password.
    op.alter_column("users", "password", existing_type=sa.String(length=255), nullable=True)

    op.create_index(op.f("ix_users_google_id"), "users", ["google_id"], unique=True)
    op.create_index(op.f("ix_users_status"), "users", ["status"])
    op.create_index(op.f("ix_users_account_type"), "users", ["account_type"])
    op.create_foreign_key(
        "users_created_by_fkey", "users", "users", ["created_by"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        "users_updated_by_fkey", "users", "users", ["updated_by"], ["id"], ondelete="SET NULL"
    )

    # -------------------------------------------------- 4. backfill `users`
    # Split the single `name` column, and normalise emails to lower case.
    bind.execute(
        sa.text(
            """
            UPDATE users SET
                email      = lower(trim(email)),
                first_name = COALESCE(NULLIF(split_part(trim(name), ' ', 1), ''), 'User'),
                last_name  = CASE
                                WHEN position(' ' in trim(name)) > 0
                                THEN trim(substring(trim(name) from position(' ' in trim(name)) + 1))
                                ELSE ''
                             END
            """
        )
    )

    # Pre-existing accounts were usable before this migration, so keep them
    # usable — activating them preserves behaviour. Only NEW accounts get the
    # INACTIVE-by-default treatment.
    bind.execute(sa.text("UPDATE users SET status = 'ACTIVE'"))

    # Hash every plaintext password, one row at a time (bcrypt is per-row).
    rows = bind.execute(sa.text("SELECT id, password FROM users")).fetchall()
    for row in rows:
        digest = _hash(row.password)
        bind.execute(
            sa.text("UPDATE users SET password = :pw WHERE id = :id"),
            {"pw": digest, "id": row.id},
        )
    print(f"[migration] hashed {len(rows)} existing user password(s)")

    # ------------------------------------------- 4b. retire the old columns
    # These MUST go before the fold in step 5: both are NOT NULL with no server
    # default, so inserting a folded admin row while they still exist fails with
    # a not-null violation. `name` has already been split above, and `role` is
    # not needed — see the note in step 6 about why old `users.role` maps to
    # `User` regardless of its value.
    op.drop_column("users", "role")
    op.drop_column("users", "name")
    postgresql.ENUM(name="user_role").drop(bind, checkfirst=True)

    # ------------------------------------- 5. fold `admin_users` into `users`
    admin_rows = bind.execute(
        sa.text(
            "SELECT id, email, password, full_name, is_active, role, "
            "failed_login_attempts, locked_until, last_login_at, last_login_ip, "
            "created_at, updated_at FROM admin_users"
        )
    ).fetchall()

    migrated: list[tuple[str, str]] = []  # (user_id, role_name)
    skipped: list[str] = []

    for row in admin_rows:
        email = (row.email or "").strip().lower()

        clash = bind.execute(
            sa.text("SELECT id FROM users WHERE email = :email"), {"email": email}
        ).fetchone()
        if clash is not None:
            # Same address already in `users`. Promote the surviving row instead
            # of creating a duplicate, and keep the stronger of the two states.
            skipped.append(email)
            migrated.append(
                (clash.id, ROLE_SUPER_ADMIN if row.role == "super_admin" else ROLE_ADMIN)
            )
            bind.execute(
                sa.text("UPDATE users SET account_type = 'staff' WHERE id = :id"),
                {"id": clash.id},
            )
            continue

        parts = (row.full_name or "").strip().split(" ", 1)
        first = parts[0] or "Admin"
        last = parts[1] if len(parts) > 1 else ""
        # `id` is preserved so tests.created_by keeps pointing at a real row.
        new_id = row.id or str(uuid.uuid4())

        bind.execute(
            sa.text(
                """
                INSERT INTO users (
                    id, email, password, first_name, last_name,
                    auth_provider, account_type, status, timezone_preference,
                    failed_login_attempts, locked_until, last_login_at, last_login_ip,
                    email_verified_at, created_at, updated_at
                ) VALUES (
                    :id, :email, :password, :first, :last,
                    'credentials', 'staff', :status, 'Asia/Kolkata',
                    :failed, :locked, :last_login_at, :last_login_ip,
                    :now, :created_at, :updated_at
                )
                """
            ),
            {
                "id": new_id,
                "email": email,
                "password": _hash(row.password),
                "first": first,
                "last": last,
                "status": "ACTIVE" if row.is_active else "INACTIVE",
                "failed": row.failed_login_attempts or 0,
                "locked": row.locked_until,
                "last_login_at": row.last_login_at,
                "last_login_ip": row.last_login_ip,
                "now": now,
                "created_at": row.created_at or now,
                "updated_at": row.updated_at or now,
            },
        )
        migrated.append(
            (new_id, ROLE_SUPER_ADMIN if row.role == "super_admin" else ROLE_ADMIN)
        )

    print(f"[migration] folded {len(admin_rows)} admin account(s) into users")
    if skipped:
        print(f"[migration] merged into existing rows by email: {', '.join(skipped)}")

    # ------------------------------------------------------ 6. assign roles
    role_ids = dict(bind.execute(sa.text("SELECT name, id FROM roles")).fetchall())

    for user_id, role_name in migrated:
        bind.execute(
            sa.text(
                "INSERT INTO user_roles (user_id, role_id) VALUES (:uid, :rid) "
                "ON CONFLICT DO NOTHING"
            ),
            {"uid": user_id, "rid": role_ids[role_name]},
        )

    # Everyone else gets `User`. The old `users.role` column had an 'admin' value
    # that NO route ever checked, so it granted nothing — mapping those rows to
    # `User` preserves their actual capability rather than inventing privilege.
    bind.execute(
        sa.text(
            "INSERT INTO user_roles (user_id, role_id) "
            "SELECT u.id, :rid FROM users u "
            "WHERE NOT EXISTS (SELECT 1 FROM user_roles ur WHERE ur.user_id = u.id) "
            "ON CONFLICT DO NOTHING"
        ),
        {"rid": role_ids[ROLE_USER]},
    )

    # Classify by email domain so staff/partner is sensible from the start.
    bind.execute(
        sa.text(
            "UPDATE users SET account_type = 'staff' "
            "WHERE lower(email) LIKE '%@leapswitch.com'"
        )
    )

    # ------------------------------------------------------------- 7. cleanup
    # `tests.created_by` pointed at admin_users; repoint it before that table goes.
    op.drop_constraint("tests_created_by_fkey", "tests", type_="foreignkey")
    op.create_foreign_key(
        "tests_created_by_fkey", "tests", "users", ["created_by"], ["id"], ondelete="SET NULL"
    )

    op.drop_table("admin_users")
    postgresql.ENUM(name="admin_role").drop(bind, checkfirst=True)

    # Server defaults were only needed to backfill NOT NULL columns; the models
    # supply Python-side defaults, so drop them to keep model and schema aligned.
    for column in ("auth_provider", "account_type", "status", "timezone_preference",
                   "failed_login_attempts"):
        op.alter_column("users", column, server_default=None)

    # first_name/last_name are NOT NULL in the model; they are populated now.
    op.alter_column(
        "users", "first_name", existing_type=sa.String(length=100), nullable=False
    )
    op.alter_column(
        "users", "last_name", existing_type=sa.String(length=100), nullable=False
    )


def downgrade() -> None:
    """Deliberately irreversible.

    Reversing this would require the original plaintext passwords, which were
    replaced by one-way bcrypt digests in step 4 and cannot be recovered. It
    would also have to decide which `users` rows to move back into `admin_users`
    after they were merged by email.

    To go back, restore the pre-migration database dump.
    """
    raise NotImplementedError(
        "Irreversible: plaintext passwords were replaced with bcrypt digests and "
        "the two account tables were merged. Restore from a backup taken before "
        "this migration instead."
    )
