"""create webhook_endpoints and webhook_deliveries

Revision ID: e83b47d1f095
Revises: d2f60a91c7e4
Create Date: 2026-08-12

LeapDesk parity Module 14 — outbound webhooks. Depends on Module 10: an endpoint
belongs to an `api_consumer`, so this migration cannot run before that table
exists, and the chain enforces it.

**Hand-written, not autogenerated**, for the same reason as the last three: the
pre-existing model/database drift makes `--autogenerate` emit dozens of unrelated
`alter_column` operations.

Two columns are ours rather than the reference's, both because we have no queue:
`webhook_deliveries.status` and `next_attempt_at`. LeapDesk infers state from the
`delivered_at`/`failed_at` pair and lets its queue own scheduling; with no worker
to own it, "what is due to be retried" has to be a question the table can answer.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e83b47d1f095"
down_revision: str | None = "d2f60a91c7e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "webhook_endpoints",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "api_consumer_id",
            sa.String(length=36),
            sa.ForeignKey("api_consumers.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=191), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        # Fernet ciphertext. Encrypted rather than hashed because the HMAC has to
        # be reproduced on every delivery — see the model docstring.
        sa.Column("secret", sa.Text(), nullable=False),
        sa.Column("events", postgresql.JSONB(), nullable=False, server_default="[]"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("last_delivery_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_count", sa.Integer(), nullable=False, server_default="0"),
        # The circuit breaker's mark. Distinct from `is_active`: one says "we gave
        # up", the other says "a person switched it off".
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_by",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="SET NULL"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_webhook_endpoints_api_consumer_id", "webhook_endpoints", ["api_consumer_id"]
    )
    op.create_index("ix_webhook_endpoints_is_active", "webhook_endpoints", ["is_active"])

    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column(
            "webhook_endpoint_id",
            sa.String(length=36),
            sa.ForeignKey("webhook_endpoints.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("event", sa.String(length=100), nullable=False),
        sa.Column("payload", postgresql.JSONB(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="pending"),
        sa.Column("response_status", sa.SmallInteger(), nullable=True),
        sa.Column("response_body", sa.Text(), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("next_attempt_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index(
        "ix_webhook_deliveries_endpoint", "webhook_deliveries", ["webhook_endpoint_id"]
    )
    op.create_index("ix_webhook_deliveries_event", "webhook_deliveries", ["event"])
    op.create_index(
        "webhook_deliveries_endpoint_created_index",
        "webhook_deliveries",
        ["webhook_endpoint_id", "created_at"],
    )
    # "What is due to be retried" — without this the sweep scans every delivery
    # ever made to find the handful that are.
    op.create_index(
        "webhook_deliveries_due_index", "webhook_deliveries", ["status", "next_attempt_at"]
    )


def downgrade() -> None:
    op.drop_index("webhook_deliveries_due_index", table_name="webhook_deliveries")
    op.drop_index("webhook_deliveries_endpoint_created_index", table_name="webhook_deliveries")
    op.drop_index("ix_webhook_deliveries_event", table_name="webhook_deliveries")
    op.drop_index("ix_webhook_deliveries_endpoint", table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index("ix_webhook_endpoints_is_active", table_name="webhook_endpoints")
    op.drop_index("ix_webhook_endpoints_api_consumer_id", table_name="webhook_endpoints")
    op.drop_table("webhook_endpoints")
