"""add partner brand assets — logo and banner bytes

Punchlist task 3.3. Six nullable columns on `partners`.

Hand-written rather than autogenerated, deliberately: `--autogenerate` still
proposes ~90 unrelated operations against this database (the drift recorded in
`5098784d1c1c`'s docstring), and six known columns are faster to write than that
output is to review.

Revision ID: e9633cd23b54
Revises: 5098784d1c1c
Create Date: 2026-08-18

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

revision: str = "e9633cd23b54"
down_revision: Union[str, None] = "5098784d1c1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Nullable throughout: a partner without a logo is the normal case, and the
    # card falls back to initials derived from the name.
    op.add_column("partners", sa.Column("logo_mime", sa.String(length=60), nullable=True))
    op.add_column("partners", sa.Column("logo_bytes", sa.LargeBinary(), nullable=True))
    op.add_column(
        "partners", sa.Column("logo_updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("partners", sa.Column("banner_mime", sa.String(length=60), nullable=True))
    op.add_column("partners", sa.Column("banner_bytes", sa.LargeBinary(), nullable=True))
    op.add_column(
        "partners", sa.Column("banner_updated_at", sa.DateTime(timezone=True), nullable=True)
    )


def downgrade() -> None:
    """Drops the assets with the columns.

    ⚠️ **This loses uploaded images.** They live in these columns and nowhere
    else, so a downgrade is not reversible for content the way a schema change
    usually is. That is the trade for storing bytes in the row; it is recorded
    here so nobody discovers it during an incident.
    """
    op.drop_column("partners", "banner_updated_at")
    op.drop_column("partners", "banner_bytes")
    op.drop_column("partners", "banner_mime")
    op.drop_column("partners", "logo_updated_at")
    op.drop_column("partners", "logo_bytes")
    op.drop_column("partners", "logo_mime")
