"""create worker_job_runs

Revision ID: f1a94c02d7b3
Revises: e83b47d1f095
Create Date: 2026-08-12

LeapDesk parity Module 16, re-scoped. The plan blocks the Queue Monitor on "we
have no queue" and warns that building it first "would produce a page that says
0 jobs forever". `app/worker.py` now runs four jobs on a timer — but a worker is
not a queue, so there is no backlog to monitor: no `queued_at`, no `attempts`, no
retry/forget/purge, because a job that is due runs and a job that failed runs
again on its next interval.

What is left is the same question with the evidence we actually have: one row per
run, written whether the job succeeded or failed. See `app/models/worker_run.py`
for the full reasoning.

Hand-written, not autogenerated — the pre-existing model/database drift makes
`--autogenerate` emit dozens of unrelated `alter_column` operations.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "f1a94c02d7b3"
down_revision: str | None = "e83b47d1f095"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "worker_job_runs",
        sa.Column("id", sa.String(length=36), primary_key=True),
        sa.Column("job", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("unit", sa.String(length=64), nullable=True),
        # Type and message only. The traceback stays in the logs — this column is
        # rendered on a screen.
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
    )
    op.create_index("ix_worker_job_runs_job", "worker_job_runs", ["job"])
    op.create_index("ix_worker_job_runs_status", "worker_job_runs", ["status"])
    op.create_index(
        "worker_job_runs_job_started_index", "worker_job_runs", ["job", "started_at"]
    )
    op.create_index("worker_job_runs_started_index", "worker_job_runs", ["started_at"])


def downgrade() -> None:
    op.drop_index("worker_job_runs_started_index", table_name="worker_job_runs")
    op.drop_index("worker_job_runs_job_started_index", table_name="worker_job_runs")
    op.drop_index("ix_worker_job_runs_status", table_name="worker_job_runs")
    op.drop_index("ix_worker_job_runs_job", table_name="worker_job_runs")
    op.drop_table("worker_job_runs")
