"""add user_sessions so tokens can be revoked

Authentication was stateless JWT with no way to un-issue a credential: logout
cleared the browser cookie and nothing else, so a captured token stayed valid for
up to an hour (access) or seven days (refresh), and changing a password evicted
nobody. This table is the server-side half that makes revocation possible — every
token carries a `sid` naming a row here, and the guard refuses a token whose row
is revoked or expired.

Hand-written rather than autogenerated: autogenerate would produce the table but
not the three indexes chosen for the specific queries that run against it, and
would not carry this note.

Indexes, and the query each serves:

  * ``user_id``              — revoke-all on password change / admin suspension,
                               and listing a user's active sessions.
  * ``expires_at``           — the purge of long-dead rows.
  * ``(user_id, revoked_at)``— the hot path for bulk revoke, which filters on
                               both. A composite beats two separate scans.

The primary-key lookup the guard performs on every authenticated request needs no
index of its own.

**No data migration.** Existing tokens carry no `sid`, so they fail closed and
those users sign in again. That is deliberate: accepting a token without a `sid`
"for compatibility" would leave a permanent bypass of the mechanism this exists
to create.

Revision ID: f3c81a5be204
Revises: e7b41c9a2d10
Create Date: 2026-08-03
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "f3c81a5be204"
down_revision: Union[str, None] = "e7b41c9a2d10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "user_sessions",
        sa.Column(
            "id",
            sa.String(length=36),
            primary_key=True,
            nullable=False,
            comment="The 'sid' claim in both the access and refresh tokens",
        ),
        sa.Column(
            "user_id",
            sa.String(length=36),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "ip_address",
            sa.String(length=45),
            nullable=True,
            comment="45 chars fits an IPv4-mapped IPv6 address",
        ),
        sa.Column(
            "user_agent",
            sa.Text(),
            nullable=True,
            comment="Untrusted self-reported text. Display only; never decide on it",
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Mirrors the refresh token's expiry; past this the session is dead",
        ),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "revoked_reason",
            sa.String(length=50),
            nullable=True,
            comment="logout | password_change | password_reset | revoked_by_admin",
        ),
    )

    op.create_index("ix_user_sessions_user_id", "user_sessions", ["user_id"])
    op.create_index("ix_user_sessions_expires_at", "user_sessions", ["expires_at"])
    op.create_index(
        "ix_user_sessions_user_id_revoked_at",
        "user_sessions",
        ["user_id", "revoked_at"],
    )


def downgrade() -> None:
    # Dropping the table signs everybody out, because every token names a row that
    # no longer exists. That is correct rather than unfortunate: without this table
    # there is no revocation, so the tokens it backed must not keep working.
    op.drop_index("ix_user_sessions_user_id_revoked_at", table_name="user_sessions")
    op.drop_index("ix_user_sessions_expires_at", table_name="user_sessions")
    op.drop_index("ix_user_sessions_user_id", table_name="user_sessions")
    op.drop_table("user_sessions")
