"""create error_groups and error_occurrences

Revision ID: f7a3d9142e60
Revises: e5c2f71a94b8
Create Date: 2026-08-11

LeapDesk parity Module 17 — Error Tracking. Columns match the reference.

**Hand-written, not autogenerated** — the standing model/database drift makes
`--autogenerate` emit ~84 unrelated `alter_column` operations against five other
tables.

**`error_occurrences.error_group_id` cascades; `user_id` does not.** Deleting a
group is a deliberate act that should take its evidence with it — a group with no
occurrences is a count with nothing behind it. Deleting a *user* must not delete
the record that an error happened, so that side is SET NULL.

**`occurrence_count` is denormalised on the group and that is on purpose.**
Occurrence rows are prunable — they are the bulky half — and the count has to
survive pruning, or an old error looks like it happened once.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f7a3d9142e60"
down_revision: str | None = "e5c2f71a94b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "error_groups",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "fingerprint", sa.String(length=32), nullable=False,
            comment="md5(exception_class|file|line|route). Excludes the message",
        ),
        sa.Column("exception_class", sa.String(length=255), nullable=False),
        sa.Column("module", sa.String(length=32), server_default="core", nullable=False),
        sa.Column("route_name", sa.String(length=191), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("path", sa.String(length=500), nullable=True),
        sa.Column("file", sa.String(length=500), nullable=False),
        sa.Column("line", sa.Integer(), nullable=False),
        sa.Column("latest_message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=20), server_default="open", nullable=False),
        sa.Column(
            "occurrence_count", sa.Integer(), server_default="0", nullable=False,
            comment="Denormalised. Occurrence rows are prunable; this count is not",
        ),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolved_by", sa.String(length=36), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["resolved_by"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("fingerprint", name="uq_error_groups_fingerprint"),
    )
    op.create_index(op.f("ix_error_groups_exception_class"), "error_groups", ["exception_class"])
    op.create_index(op.f("ix_error_groups_module"), "error_groups", ["module"])
    op.create_index(op.f("ix_error_groups_status"), "error_groups", ["status"])
    op.create_index(op.f("ix_error_groups_first_seen_at"), "error_groups", ["first_seen_at"])
    op.create_index(op.f("ix_error_groups_last_seen_at"), "error_groups", ["last_seen_at"])
    op.create_index("ix_error_groups_status_seen", "error_groups", ["status", "last_seen_at"])

    op.create_table(
        "error_occurrences",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("error_group_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("ip", sa.String(length=45), nullable=True),
        sa.Column("url", sa.String(length=1000), nullable=True),
        sa.Column("method", sa.String(length=10), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("stack_trace", sa.Text(), nullable=True),
        sa.Column(
            "context", postgresql.JSONB(astext_type=sa.Text()), nullable=True,
            comment="User agent and referer ONLY. Never request input",
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["error_group_id"], ["error_groups.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_error_occurrences_occurred_at"), "error_occurrences", ["occurred_at"])
    op.create_index(
        "ix_error_occ_group_time", "error_occurrences", ["error_group_id", "occurred_at"]
    )


def downgrade() -> None:
    op.drop_index("ix_error_occ_group_time", table_name="error_occurrences")
    op.drop_index(op.f("ix_error_occurrences_occurred_at"), table_name="error_occurrences")
    op.drop_table("error_occurrences")
    op.drop_index("ix_error_groups_status_seen", table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_last_seen_at"), table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_first_seen_at"), table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_status"), table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_module"), table_name="error_groups")
    op.drop_index(op.f("ix_error_groups_exception_class"), table_name="error_groups")
    op.drop_table("error_groups")
